// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resort.Datos;

#nullable disable

namespace Resort.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260505000712_AgregarNumeroVilla")]
    partial class AgregarNumeroVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resort.Modelos.NumeroVilla", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<string>("DetalleEspecial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("NumeroVillas");
                });

            modelBuilder.Entity("Resort.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "Amenidad de la Villa 1",
                            Detalle = "Detalle de la Villa 1",
                            FechaActualizacion = new DateTime(2026, 5, 4, 21, 7, 11, 98, DateTimeKind.Local).AddTicks(6829),
                            FechaCreacion = new DateTime(2026, 5, 4, 21, 7, 11, 98, DateTimeKind.Local).AddTicks(6815),
                            ImageUrl = "https://example.com/villa1.jpg",
                            MetrosCuadrados = 50.0,
                            Nombre = "Villa 1",
                            Ocupantes = 3,
                            RowVersion = new byte[0],
                            Tarifa = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "Amenidad de la Villa 2",
                            Detalle = "Detalle de la Villa 2",
                            FechaActualizacion = new DateTime(2026, 5, 4, 21, 7, 11, 98, DateTimeKind.Local).AddTicks(6832),
                            FechaCreacion = new DateTime(2026, 5, 4, 21, 7, 11, 98, DateTimeKind.Local).AddTicks(6831),
                            ImageUrl = "https://example.com/villa2.jpg",
                            MetrosCuadrados = 60.0,
                            Nombre = "Villa 2",
                            Ocupantes = 4,
                            RowVersion = new byte[0],
                            Tarifa = 150.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "Amenidad de la Villa 3",
                            Detalle = "Detalle de la Villa 3",
                            FechaActualizacion = new DateTime(2026, 5, 4, 21, 7, 11, 98, DateTimeKind.Local).AddTicks(6833),
                            FechaCreacion = new DateTime(2026, 5, 4, 21, 7, 11, 98, DateTimeKind.Local).AddTicks(6833),
                            ImageUrl = "https://example.com/villa3.jpg",
                            MetrosCuadrados = 70.0,
                            Nombre = "Villa 3",
                            Ocupantes = 5,
                            RowVersion = new byte[0],
                            Tarifa = 200.0
                        });
                });

            modelBuilder.Entity("Resort.Modelos.NumeroVilla", b =>
                {
                    b.HasOne("Resort.Modelos.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
